#!/bin/bash
# Email Debugging Script
# This script helps debug email sending issues

set -e

PROJECT_ID="sfrqhzqhmqbgpbmyucph"

echo "======================================"
echo "Email Sending Debug Checklist"
echo "======================================"
echo ""

echo "1. Check Edge Functions are deployed:"
echo "   Go to: https://app.supabase.com/project/$PROJECT_ID/functions"
echo "   Verify these functions exist:"
echo "   - submit-estimation"
echo "   - book-appointment"
echo "   - admin-photo-links"
echo ""

echo "2. Check Edge Function Secrets are set:"
echo "   Go to: https://app.supabase.com/project/$PROJECT_ID/settings/functions"
echo "   Required secrets:"
echo "   - RESEND_API_KEY (your Resend API key)"
echo "   - RESEND_FROM (e.g., Meinautoverkauf <no-reply@meinautoverkauf.de>)"
echo "   - SUPABASE_ANON_KEY (same as VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY)"
echo ""

echo "3. Check if data is being saved:"
echo "   Go to: https://app.supabase.com/project/$PROJECT_ID/editor"
echo "   Check these tables for recent data:"
echo "   - estimations (should have rows from form submissions)"
echo "   - appointments (should have rows from bookings)"
echo "   - email_log (should have entries - check 'error' column)"
echo ""

echo "4. Check Edge Function Logs:"
echo "   Go to: https://app.supabase.com/project/$PROJECT_ID/logs/edge-functions"
echo "   Look for errors in submit-estimation and book-appointment logs"
echo ""

echo "5. Test Edge Functions manually:"
echo "   Use the Supabase Dashboard to invoke the functions with test data"
echo ""

echo "======================================"
echo "Quick Deploy Commands"
echo "======================================"
echo ""
echo "If functions are NOT deployed, run:"
echo "  cd supabase"
echo "  npx supabase login"
echo "  ./deploy.sh"
echo ""

echo "======================================"
echo "Troubleshooting Common Issues"
echo "======================================"
echo ""
echo "Issue: 'Functions not found'"
echo "  Solution: Deploy Edge Functions using deploy.sh"
echo ""
echo "Issue: 'Data not saved'"
echo "  Solution: Check browser console for errors"
echo "  Solution: Verify frontend is calling the functions"
echo ""
echo "Issue: 'Email not sent but data saved'"
echo "  Solution: Check RESEND_API_KEY is set correctly"
echo "  Solution: Check email_log table for error messages"
echo "  Solution: Verify Resend API key is valid"
echo ""
echo "Issue: 'Auth errors in admin-photo-links'"
echo "  Solution: Set SUPABASE_ANON_KEY in Edge Function secrets"
echo ""

echo "======================================"
echo "Next Steps"
echo "======================================"
echo ""
echo "1. Visit Supabase Dashboard and check items 1-4 above"
echo "2. Look at browser console when submitting form"
echo "3. Check email_log table in database"
echo "4. Deploy functions if needed: ./supabase/deploy.sh"
echo "5. Set secrets in Supabase Dashboard if missing"
echo ""
